-- RecallAI initial schema.
-- Flyway owns the schema; Hibernate runs in validate mode and never alters tables.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE decks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    name        VARCHAR(150)  NOT NULL,
    description TEXT,
    subject     VARCHAR(100),
    tags        TEXT[]        NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_decks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_decks_user_id ON decks (user_id);
CREATE INDEX idx_decks_tags ON decks USING GIN (tags);

CREATE TABLE cards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id      BIGINT        NOT NULL,
    question     TEXT          NOT NULL,
    answer       TEXT          NOT NULL,
    explanation  TEXT,
    topic        VARCHAR(150),
    tags         TEXT[]        NOT NULL DEFAULT '{}',
    -- SM-2 scheduling state. Defaults are the canonical SM-2 starting values.
    ease_factor  NUMERIC(4, 2) NOT NULL DEFAULT 2.50,
    interval     INTEGER       NOT NULL DEFAULT 0,
    repetitions  INTEGER       NOT NULL DEFAULT 0,
    due_date     DATE          NOT NULL DEFAULT CURRENT_DATE,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_cards_deck FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE,
    CONSTRAINT ck_cards_ease_factor CHECK (ease_factor >= 1.30),
    CONSTRAINT ck_cards_interval CHECK (interval >= 0),
    CONSTRAINT ck_cards_repetitions CHECK (repetitions >= 0)
);
CREATE INDEX idx_cards_deck_id ON cards (deck_id);
CREATE INDEX idx_cards_deck_due ON cards (deck_id, due_date);
CREATE INDEX idx_cards_tags ON cards USING GIN (tags);
CREATE INDEX idx_cards_topic ON cards (topic);

CREATE TABLE review_history (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id              BIGINT        NOT NULL,
    user_id              BIGINT        NOT NULL,
    quality_score        SMALLINT      NOT NULL,
    previous_interval    INTEGER       NOT NULL,
    new_interval         INTEGER       NOT NULL,
    previous_ease_factor NUMERIC(4, 2) NOT NULL,
    new_ease_factor      NUMERIC(4, 2) NOT NULL,
    reviewed_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_review_history_card FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_history_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_review_history_quality CHECK (quality_score BETWEEN 0 AND 5)
);
CREATE INDEX idx_review_history_card_id ON review_history (card_id);
CREATE INDEX idx_review_history_user_reviewed ON review_history (user_id, reviewed_at DESC);

CREATE TABLE quizzes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id    BIGINT       NOT NULL,
    title      VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_quizzes_deck FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE
);
CREATE INDEX idx_quizzes_deck_id ON quizzes (deck_id);

CREATE TABLE quiz_questions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id        BIGINT   NOT NULL,
    question       TEXT     NOT NULL,
    option_a       TEXT     NOT NULL,
    option_b       TEXT     NOT NULL,
    option_c       TEXT     NOT NULL,
    option_d       TEXT     NOT NULL,
    -- Index 0..3 into (option_a, option_b, option_c, option_d).
    correct_answer SMALLINT NOT NULL,
    explanation    TEXT     NOT NULL,
    CONSTRAINT fk_quiz_questions_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes (id) ON DELETE CASCADE,
    CONSTRAINT ck_quiz_questions_correct_answer CHECK (correct_answer BETWEEN 0 AND 3)
);
CREATE INDEX idx_quiz_questions_quiz_id ON quiz_questions (quiz_id);

CREATE TABLE quiz_attempts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id         BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    score           INTEGER     NOT NULL,
    total_questions INTEGER     NOT NULL,
    completed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_quiz_attempts_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes (id) ON DELETE CASCADE,
    CONSTRAINT fk_quiz_attempts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_quiz_attempts_score CHECK (score >= 0 AND score <= total_questions)
);
CREATE INDEX idx_quiz_attempts_quiz_id ON quiz_attempts (quiz_id);
CREATE INDEX idx_quiz_attempts_user_completed ON quiz_attempts (user_id, completed_at DESC);

-- Cache of validated Claude responses keyed by normalized-content hash.
-- Rows are content-addressed, never user-addressed, so identical study
-- material from two users shares one AI call.
CREATE TABLE ai_cache (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_hash   CHAR(64)     NOT NULL,
    operation_type VARCHAR(50)  NOT NULL,
    model          VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(20)  NOT NULL,
    response_json  JSONB        NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_ai_cache_key UNIQUE (content_hash, operation_type, model, prompt_version)
);
