-- Per-question results for a quiz attempt, so the review screen can show which answers
-- were wrong and why, and how long the attempt took.

ALTER TABLE quiz_attempts
    ADD COLUMN duration_seconds INTEGER,
    ADD CONSTRAINT ck_quiz_attempts_duration CHECK (duration_seconds IS NULL OR duration_seconds >= 0);

CREATE TABLE quiz_attempt_answers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id      BIGINT   NOT NULL,
    question_id     BIGINT   NOT NULL,
    -- NULL when the question was skipped; always counts as incorrect.
    selected_answer SMALLINT,
    correct         BOOLEAN  NOT NULL,
    CONSTRAINT fk_quiz_attempt_answers_attempt FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (id) ON DELETE CASCADE,
    CONSTRAINT fk_quiz_attempt_answers_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE,
    CONSTRAINT ck_quiz_attempt_answers_selected CHECK (selected_answer IS NULL OR selected_answer BETWEEN 0 AND 3),
    CONSTRAINT uk_quiz_attempt_answers UNIQUE (attempt_id, question_id)
);
CREATE INDEX idx_quiz_attempt_answers_attempt ON quiz_attempt_answers (attempt_id);
