-- Phase 3 of the adaptive upgrade: mistakes captured from quizzes (and later mock exams), each of
-- which can be turned into an explanatory flashcard that SM-2 then schedules.
CREATE TABLE mistakes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id          BIGINT       REFERENCES decks (id) ON DELETE SET NULL,
    quiz_question_id BIGINT       REFERENCES quiz_questions (id) ON DELETE SET NULL,
    source           VARCHAR(20)  NOT NULL,
    question         TEXT         NOT NULL,
    given_answer     TEXT,
    correct_answer   TEXT         NOT NULL,
    explanation      TEXT,
    topic            VARCHAR(150),
    occurrences      INTEGER      NOT NULL DEFAULT 1,
    status           VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    card_id          BIGINT       REFERENCES cards (id) ON DELETE SET NULL,
    first_missed_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_missed_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    resolved_at      TIMESTAMPTZ,
    CONSTRAINT ck_mistakes_source CHECK (source IN ('QUIZ', 'MOCK_EXAM')),
    CONSTRAINT ck_mistakes_status CHECK (status IN ('OPEN', 'CONVERTED', 'DISMISSED')),
    CONSTRAINT ck_mistakes_occurrences CHECK (occurrences >= 1)
);

-- One mistake row per quiz question and user; repeat misses bump occurrences instead.
CREATE UNIQUE INDEX uq_mistakes_user_quiz_question ON mistakes (user_id, quiz_question_id)
    WHERE quiz_question_id IS NOT NULL;
CREATE INDEX idx_mistakes_user_status ON mistakes (user_id, status, last_missed_at DESC);

-- Cards remember where they came from so mistake-derived cards can be told apart.
ALTER TABLE cards
    ADD COLUMN origin VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN mistake_id BIGINT REFERENCES mistakes (id) ON DELETE SET NULL,
    ADD CONSTRAINT ck_cards_origin CHECK (origin IN ('MANUAL', 'AI', 'MISTAKE'));
