-- Phase 4 of the adaptive upgrade: exam study plans and their dated tasks.
CREATE TABLE study_plans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    exam_name        VARCHAR(150) NOT NULL,
    exam_date        DATE         NOT NULL,
    topics           TEXT[]       NOT NULL DEFAULT '{}',
    knowledge_level  VARCHAR(20)  NOT NULL,
    minutes_per_day  INTEGER      NOT NULL,
    preferred_days   INTEGER[]    NOT NULL DEFAULT '{1,2,3,4,5,6,7}',
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    summary          TEXT,
    topic_advice     JSONB        NOT NULL DEFAULT '[]'::jsonb,
    ai_generated     BOOLEAN      NOT NULL DEFAULT FALSE,
    generated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_study_plans_level CHECK (knowledge_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT ck_study_plans_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT ck_study_plans_minutes CHECK (minutes_per_day BETWEEN 10 AND 720)
);

CREATE TABLE study_plan_tasks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT       NOT NULL REFERENCES study_plans (id) ON DELETE CASCADE,
    scheduled_date DATE         NOT NULL,
    sort_order     INTEGER      NOT NULL,
    task_type      VARCHAR(20)  NOT NULL,
    topic          VARCHAR(150),
    title          VARCHAR(200) NOT NULL,
    description    TEXT,
    minutes        INTEGER      NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    completed_at   TIMESTAMPTZ,
    CONSTRAINT ck_study_plan_tasks_type CHECK (task_type IN
        ('REVIEW_DUE', 'LEARN_TOPIC', 'PRACTICE_QUIZ', 'REVIEW_MISTAKES', 'MOCK_EXAM', 'FINAL_REVISION')),
    CONSTRAINT ck_study_plan_tasks_status CHECK (status IN ('PENDING', 'DONE', 'SKIPPED')),
    CONSTRAINT ck_study_plan_tasks_minutes CHECK (minutes > 0)
);

CREATE INDEX idx_study_plans_user_status ON study_plans (user_id, status, created_at DESC);
CREATE INDEX idx_study_plan_tasks_plan_date ON study_plan_tasks (plan_id, scheduled_date, sort_order);
