-- Phase 5 of the adaptive upgrade: timed mock exams with mixed question types. One attempt per
-- exam, so each question row also holds the answer given and whether it was correct.
CREATE TABLE mock_exams (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id          BIGINT       REFERENCES decks (id) ON DELETE SET NULL,
    title            VARCHAR(200) NOT NULL,
    topic            VARCHAR(150),
    difficulty       VARCHAR(10)  NOT NULL,
    duration_minutes INTEGER      NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'IN_PROGRESS',
    started_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    submitted_at     TIMESTAMPTZ,
    time_taken_seconds INTEGER,
    timed_out        BOOLEAN      NOT NULL DEFAULT FALSE,
    score            INTEGER      NOT NULL DEFAULT 0,
    total_questions  INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_mock_exams_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'EXPERT')),
    CONSTRAINT ck_mock_exams_status CHECK (status IN ('IN_PROGRESS', 'SUBMITTED')),
    CONSTRAINT ck_mock_exams_duration CHECK (duration_minutes BETWEEN 5 AND 180),
    CONSTRAINT ck_mock_exams_score CHECK (score >= 0 AND score <= total_questions)
);

CREATE TABLE mock_exam_questions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id            BIGINT      NOT NULL REFERENCES mock_exams (id) ON DELETE CASCADE,
    sort_order         INTEGER     NOT NULL,
    question_type      VARCHAR(20) NOT NULL,
    question           TEXT        NOT NULL,
    options            TEXT[]      NOT NULL DEFAULT '{}',
    correct_option     SMALLINT,
    correct_answer     TEXT,
    acceptable_answers TEXT[]      NOT NULL DEFAULT '{}',
    explanation        TEXT        NOT NULL,
    topic              VARCHAR(150),
    selected_option    SMALLINT,
    answer_text        TEXT,
    correct            BOOLEAN,
    CONSTRAINT ck_mock_exam_questions_type CHECK (question_type IN ('MCQ', 'TRUE_FALSE', 'SHORT_ANSWER'))
);

CREATE INDEX idx_mock_exams_user ON mock_exams (user_id, created_at DESC);
CREATE INDEX idx_mock_exam_questions_exam ON mock_exam_questions (exam_id, sort_order);

-- Wrong exam answers become mistakes too.
ALTER TABLE mistakes ADD COLUMN mock_exam_question_id BIGINT REFERENCES mock_exam_questions (id) ON DELETE SET NULL;
CREATE UNIQUE INDEX uq_mistakes_user_exam_question ON mistakes (user_id, mock_exam_question_id)
    WHERE mock_exam_question_id IS NOT NULL;
